[package]
name = "segment"
version = "0.1.0"
authors = ["Richard Giliam <nirosys@gmail.com>"]
edition = "2018"

[dependencies]
segment-derive = { path = "segment-derive" }

[[examples]]
name = "builder"
path = "examples/builder.rs"
